---@type LazySpec
return {
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = {
      ensure_installed = {
        "astro-language-server",
        "basedpyright",
        "black",
        "codelldb",
        "css-lsp",
        "css-variables-language-server",
        "debugpy",
        "deno",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "dotenv-linter",
        "elixir-ls",
        "emmet-ls",
        "eslint-lsp",
        "html-lsp",
        "htmx-lsp",
        "isort",
        "js-debug-adapter",
        "json-lsp",
        "kotlin-language-server",
        "lua-language-server",
        "prettierd",
        "prisma-language-server",
        "selene",
        "stylua",
        "tailwindcss-language-server",
        "taplo",
        "tree-sitter-cli",
        "typescript-language-server",
        "vtsls",
        "zls",
      },
    },
  },
}
